config/routes.rb
Rails.application.routes.draw do
  root 'prefectures#index'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/napolipizza/sitemaps/sitemap.xml.gz")

  resources :users
  resources :prefectures, only: %i[index show]
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show destroy], shallow: true
    get 'visits', on: :collection
    resource :visit, only: %i[create destroy]
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :prefecture
  has_many :posts
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_params_for_google_map, only: [:show]

  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).order(id: :asc)
  end

  def show
    @shop = Shop.find(params[:id])
    gon.shop_lat = @shop.latitude
    gon.shop_lng = @shop.longitude
    gon.shop_id = @shop.id
    @posts = @shop.posts.order(created_at: :desc)
  end

  def visits
    @visited_shops = current_user.visited_shops.order(created_at: :desc)
  end

  private

  def set_params_for_google_map
    @shop = Shop.find(params[:id])
    gon.center_of_map_lat = @shop.latitude
    gon.center_of_map_lng = @shop.longitude
    gon.zoom_level_of_map = Settings.shop[:zoom_level_of_map]
    gon.shops_on_map = Shop.all
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_unvisit.html.erb
<%= link_to shop_visit_path(@shop), method: :delete, data: {confirm: "行った！を取り消しますか？"} do %>
   <button class='btn btn-dark rounded-pill'>訪問済み</button>
<% end %>

app/views/shops/_visit.html.erb
<button id='button' class='btn btn-success rounded-pill'>行った！</button>

app/views/shops/_visit_button.html.erb
<% if current_user.visit?(@shop) %>
  <%= render 'unvisit', { shop: @shop } %>
<% else %>
  <%= render 'visit', { shop: @shop } %>
<% end %>

app/views/shops/index.html.erb
<div class="container pt-3">
  <div class="row">
    <div class='col py-3'>
      <%= render 'shared/search_form', url: shops_path %>
    </div>
    <% if @shops.present? %>
      <div class='table-responsive'>
        <table class="table table-striped table-dark table-hover">
          <thead>
            <tr>
              <th scope="col"><%= (t 'shops.index.name') %></th>
              <th scope="col"><%= (t 'shops.index.address') %></th>
            </tr>
          </thead>
          <% @shops.each do |shop| %>
          <tbody>
            <tr>
              <td scope="row"><%= link_to shop.name, shop_path(shop), 'data-turbolinks': false, class: 'text-white' %></td>
              <td><%= shop.address %></td>
            </tr>

          </tbody>
          <% end %>
        </table>
      <% else %>
        <h3 class='font-weight-bold col-12'><%= (t 'shops.index.search_result') %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/show.html.erb
<% set_meta_tags title: @shop.name %>
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <h3 class=" mb-3 mt-2 text-justify"><%= @shop.name %></h3>
    </div>

      <div class='col-4 col-md-3 col-lg-2 mb-3'>
        <%= link_to "https://twitter.com/share?url=#{request.url}/&text=#{@shop.name}%0aお気に入りのナポリピッツァ協会認定店を共有しよう。%0a&hashtags=真のナポリピッツァ部,真のナポリピッツァ協会 ", title: 'Twitter', target: '_blank', class: 'btn btn-outline-primary rounded-pill' do %>
          <i class="fab fa-twitter"></i>
          <span><%= (t 'shops.show.share') %></span>
        <% end %>
      </div>
      <div class="col-4 col-md-3 col-lg-2 mb-3">
      <% if logged_in? %>
        <%= render 'visit_button', shop: @shop %>
      <% else %>
        <%= render 'visit', { shop: @shop } %>
      <% end %>
      </div>
      <div class="col-4 col-md-3 col-lg-2 mb-3">
        <%= link_to '投稿する', new_shop_post_path(@shop), class: 'btn btn-warning rounded-pill', 'data-turbolinks': false %>
      </div>


    <div class='table-responsive justify-content-center'>
      <table class="table table-striped table-dark">
        <tbody>
          <tr>
            <th><%= (t 'shops.show.tel') %></th>
            <td><%= @shop.tel_number %></td>
          </tr>
          <tr>
            <th class="text-nowrap"><%= (t 'shops.show.address') %></th>
            <td><%= @shop.address %></td>
          </tr>
          <tr>
            <th><%= (t 'shops.show.access') %></th>
            <td><%= @shop.access %></td>
          </tr>
          <tr>
            <th><%= (t 'shops.show.open') %></th>
            <td><%= simple_format(h(@shop.open), {}, sanitize: false, wrapper_tag: "div") %></td>
          </tr>
          <tr>
            <th><%= (t 'shops.show.close') %></th>
            <td><%= @shop.close %></td>
          </tr>
          <tr>
            <th><%= (t 'shops.show.member_number') %></th>
            <td><%= @shop.member_number %></td>
          </tr>
          <tr>
            <th><%= (t 'shops.show.member_since') %></th>
            <td><%= @shop.member_since %></td>
          </tr>
          <tr>
            <th><%= (t 'shops.show.pizza_maker') %></th>
            <td><%= @shop.pizza_maker %></td>
          </tr>
          <tr>
            <th><%= (t 'shops.show.oven_used') %></th>
            <td><%= @shop.oven_used %></td>
          </tr>
          <tr>
            <th ><%= (t 'shops.show.url') %></th>
            <td><%= link_to @shop.url,@shop.url, class: 'text-white' %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div id='map' class='mb-4 '></div>
    <div class='w-100 mb-3 row'>
      <p class='font-weight-bold ml-3 col'>部員口コミ</p>
      <%= link_to '投稿する', new_shop_post_path(@shop), class: 'btn btn-warning rounded-pill', 'data-turbolinks': false %>
    </div>
    <% if @posts.blank? %>
      <p>まだ口コミ投稿がありません</p>
    <% else %>
        <%= render 'posts/post' %>
    <% end %>
  </div>
</div>

app/views/shops/visits.html.erb
<div class="container pt-3">
  <div class="row">
    <p class='font-weight-bold'><%= '訪問済み店舗'%></p>
    <div class='table-responsive'>
      <% if @visited_shops.present? %>
      <table class="table table-striped table-dark table-hover">
        <thead>
          <tr>
            <th scope="col"><%= (t 'shops.index.name') %></th>
            <th scope="col"><%= (t 'shops.index.address') %></th>
          </tr>
        </thead>
        <tbody>
        <% @visited_shops.each do |visited_shop| %>
          <tr>
            <td scope="row"><%= link_to visited_shop.name, shop_path(visited_shop), 'data-turbolinks': false, class: 'text-white' %></td>
            <td><%= visited_shop.address %></td>
          </tr>
          <% end %>
        <% else %>
          <h3>訪問済みの店舗はありません</h3>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>