config/routes.rb
Rails.application.routes.draw do
  root 'prefectures#index'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/napolipizza/sitemaps/sitemap.xml.gz")

  resources :users
  resources :prefectures, only: %i[index show]
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show destroy], shallow: true
    get 'visits', on: :collection
    resource :visit, only: %i[create destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :visits, dependent: :destroy
  has_many :visited_shops, through: :visits, source: :shop
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications


  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }
  validates :profile, length: { maximum: 3000 }

  enum status: { begginer: 0, normal: 1, regular: 2, ace: 3, sub_leader: 4, leader: 5, coach: 6 }

  def visit(shop)
    visited_shops << shop
  end

  def unvisit(shop)
    visited_shops.destroy(shop)
  end

  def visit?(shop)
    visited_shops.include?(shop)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: '入部しました'
    else
      flash.now[:danger] = '入部に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to @user, success: '更新しました'
    else
      flash.now[:danger] = '編集に失敗しました'
      render 'edit'
    end
  end

  private


  def user_params
    params.require(:user).permit(:email, :name, :profile, :avatar,:avatar_cache, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_status(user)
    visited_count = user.visited_shops.count
    case visited_count
    when 0..2
        user.status = 0
    when 3..6
        user.status = 1
    when 7..12
        user.status = 2
    when 13..19
        user.status = 3
    when 20..29
        user.status = 4
    when 30..39
        user.status = 5
    else
        user.status = 6
    end
    user.status_i18n
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row form-height">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h2 class='my-4'><%= t '.title' %></h2>
      <%= form_with model: @user, local: true do |f| %>
         <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control my-2' %>
          <%= f.label :profile %>
          <%= f.text_area :profile, class: 'form-control my-2', size: "70x10" %>
        </div>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, onchange: 'previewImage()', class: 'form-control my-2', accept: 'image/*' %>
          <%= f.hidden_field :avatar_cache %>
        </div>
        <div class='mt-3 mb-3'>
          <%= image_tag @user.avatar.url,
                                id: 'preview',
                              size: '150x150',
                             class: 'rounded-circle my-3' %>
        </div>
        <%= f.submit (t 'users.edit.update'), class: 'btn btn-dark' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row form-height">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class='mt-3'><%= t '.title' %></h1>
      <%= form_with model: @user, local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit (t 'defaults.register'), class: 'btn btn-dark' %>
      <% end %>
      <div class="mt-4">
        <%= link_to auth_at_provider_path(provider: :twitter), class: 'btn btn-primary' do %>
          <i class="fab fa-twitter"></i>
          <span>Twitterアカウントで登録</span>
        <% end %>
      </div>
      <div class='text-center my-2'>
        <%= link_to (t '.to_login_page'), login_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='bg-white rounded mt-3'>
      <p class='font-weight-bold float-left mt-3 ml-3'>真のナポリピッツァ部員</p>
      <% if current_user?(@user) %>
        <%= link_to '編集', edit_user_path(current_user), class: 'btn btn-success float-right mt-3 mr-3' %>
      <% end %>
      </div>
      <div class='col-12 col-sm-5 col-md-3 mb-3 bg-white text-center rounded'>
        <%= image_tag @user.avatar.url, class: 'rounded-circle mt-2 ml-1',size: '130x130' %>
        <p class='text-center font-weight-bold pt-2'><%= @user.name %>(<%= user_status(@user) %>)</p>
      <% if current_user?(@user) %>
        <p><%= link_to '訪問店舗確認'"(#{@user.visited_shops.count}店舗達成)", visits_shops_path,'data-turbolinks': false, class: 'text-dark'%></p>
      <% end %>
      </div>
      <div class='col-12 col-sm-7 col-md-9 pt-3 mb-3 bg-white rounded'>
        <p class='font-weight-bold mb-0'>プロフィール</p><br>
        <p class ='text-jsutify text-left'><%= simple_format(h(@user.profile)) %></p>
      </div>
    </div>
    <h4 class='my-3'>投稿一覧</h4>
    <%= render 'posts/post' %>
  </div>
</div>