config/routes.rb
Rails.application.routes.draw do
  root 'prefectures#index'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/napolipizza/sitemaps/sitemap.xml.gz")

  resources :users
  resources :prefectures, only: %i[index show]
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show destroy], shallow: true
    get 'visits', on: :collection
    resource :visit, only: %i[create destroy]
  end
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class='navbar navbar-expand-md top-logo nav-menu'>
    <div class="container">
      <%= link_to root_path, class: 'navbar-brand text-white header-font','data-turbolinks': false do %>
        <%= image_tag 'header-logo.png', size: "270x56"  %>
      <% end %>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item d-md-flex">
            <%= link_to (t 'shops.index.title'), shops_path, class: 'ml-2 mt-1 text-white  header-font nav-link', 'data-turbolinks': false %>
            <%= link_to (t 'users.new.header_title') , new_user_path, class: 'ml-2 mt-1 text-white  header-font nav-link', 'data-turbolinks': false %>
            <%= link_to (t 'defaults.login'), login_path, class: 'ml-2 mt-1 text-white  header-font nav-link', 'data-turbolinks': false %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
   <div id="error_messages" class="alert alert-danger">
     <ul class="mb-0">
       <% object.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-bottom bg-dark">
  <div class='container text-white text-center pt-2'>
    <div class='row'>
      <%= link_to "https://twitter.com/share?url=#{request.url}&text=%23真のナポリピッツァ部%20は真のナポリピッツァ協会認定店を簡単に探せるサービスです。%0aお気に入りの%20%23真のナポリピッツァ協会認定店%20を共有しよう。", title: 'Twitter', target: '_blank', class: 'text-white p-1 col-sm' do %>
        <i class="fab fa-twitter"></i>
      <% end %>
      <%= link_to (t 'static_pages.privacy.title'), privacy_path, class: 'text-white p-1 col-sm' %>
      <%= link_to (t 'static_pages.terms.title'), terms_path, class: 'text-white p-1 col-sm' %>
      <%= link_to (t 'static_pages.inquiry.title'), 'https://docs.google.com/forms/d/e/1FAIpQLScFAFOkoHimw2hOpkOtW85zhzpXPaq_HK9buqYlkO0pzY-4kw/viewform?usp=sf_link', class: 'text-white p-1 col-sm' %>
    </div>
  </div>
  <div class='row'>
    <div class='text-white text-center col-12 pt-2'>
      <p>Copyright © 2022. 真のナポリピッツァ部</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-md top-logo nav-menu'>
    <div class="container">
      <%= link_to root_path, class: 'navbar-brand text-white header-font','data-turbolinks': false do %>
        <%= image_tag 'header-logo.png', size: "270x56" %>
      <% end %>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item d-md-flex">
            <%= link_to (t 'shops.index.title'), shops_path, class: 'ml-2 mt-1 text-white  header-font nav-link', 'data-turbolinks': false %>
            <%= link_to (t 'profiles.show.title'), current_user, class: 'ml-2 mt-1 text-white  header-font nav-link', 'data-turbolinks': false %>
            <%= link_to (t 'defaults.logout'), logout_path, class: 'ml-2 mt-1 text-white  header-font nav-link', 'data-turbolinks': false, method: :delete %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class='input-group'>
    <div class="col-5 d-inline-block mb-2  pr-0">
      <%= f.search_field :name_or_address_cont, method: :get, local: true, class: "form-control text-justify", placeholder: "地名・店名" %>
    </div>
    <div class="col-5 d-inline-block pr-0">
      <%= f.select :address_cont, options_from_collection_for_select(Prefecture.all, :name, :name), { include_blank: '都道府県を選択' }, { class: 'form-control text-justify' } %>
    </div>
    <div class="d-inline-block input-group-append">
      <%= f.submit '検索', class: "col-auto btn btn-dark"%>
    </div>
  </div>
<% end %>