config/routes.rb
Rails.application.routes.draw do
  root 'prefectures#index'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/napolipizza/sitemaps/sitemap.xml.gz")

  resources :users
  resources :prefectures, only: %i[index show]
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show destroy], shallow: true
    get 'visits', on: :collection
    resource :visit, only: %i[create destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploaders :image, ImageUploader
  serialize :image, JSON

  belongs_to :user
  belongs_to :shop

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true, length: { maximum: 10000 }
  validate :validate_number_of_files

  FILE_NUMBER_LIMIT = 4

  def set_date
    created_at.strftime("%Y年%m月%d日 %R")
  end

  private

  def validate_number_of_files
    return if image.length <= FILE_NUMBER_LIMIT
      errors.add(:image, "に添付できる画像は#{FILE_NUMBER_LIMIT}件までです。")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:show]

  def new
    @shop = Shop.find(params[:shop_id])
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to shop_path(@post.shop), success: '投稿しました'
    else
      @shop = Shop.find(params[:shop_id])
      flash.now['danger'] = '投稿に失敗しました'
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to shop_path(@post.shop.id), success: '投稿を削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image_cache, :shop_id, { image: [] })
  end
end

app/views/posts/_post.html.erb
<div class="mb-3 w-100">
  <% @posts.each do |post| %>
    <div class='bg-white rounded mb-3 p-4 '>
      <p class='small'><%= link_to post.shop.name, shop_path(post.shop.id), class: 'text-dark', 'data-turbolinks': false %></p>
      <%= link_to user_path(post.user) do %>
        <div class='font-weight-bold  text-center col-12 col-sm-3'>
          <%= image_tag post.user.avatar_url, class: 'rounded-circle my-2', size: '120x120' %>
          <p class='text-dark'><%= post.user.name %>(<%= user_status(post.user) %>)</p>
      <% end %>
        </div>
      <p class='mt-4 ml-3 font-weight-bold'><%= post.title %></p>

      <p class='text-jsutify'><%= simple_format(h(post.body)) %></p>
      <% post.image.each do |image| %>
        <%= image_tag image.url, class: 'rounded m-1', size: '250x200' %>
      <%end%>
      <div>
        <%= link_to '詳細表示', post_path(post), class: 'ml-1' , 'data-turbolinks': false %>
        <p class='mb-0 mt-3'><%= post.set_date %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post_form.html.erb
<div class="container">
  <div class="row form-height">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <p class='mt-3 font-weight-bold'>お店に口コミを投稿</p>
      <p class='mt-3 font-weight-bold'><%= link_to @shop.name, shop_path(@shop),'data-turbolinks': false %></p>
      <%= form_with model: @post, url: [@shop, @post], local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: 10 %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, multiple: true, onchange: 'previewImage()', class: 'form-control ', accept: 'image/*' %>
          <%= f.hidden_field :image_cache %>
        </div>
        <%= f.hidden_field :shop_id , value: @shop.id %>
        <%= f.submit (t 'post.new.post'), class: 'mt-3 btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'posts/post_form' %>

app/views/posts/show.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="border-bottom w-100 mt-4 ml-4">
      <p class='font-weight-bold'>部員口コミ</p>
      <p class='mt-3 font-weight-bold'><%= link_to @post.shop.name, shop_path(@post.shop.id), 'data-turbolinks': false %></p>
    </div>
    <div class="mb-3 w-100">
      <div class='bg-white rounded mb-3 p-3'>
        <div class='float-right'>
          <%= link_to "https://twitter.com/share?url=#{request.url}&text=#{@post.user.name}さんが口コミ投稿をしてくれました!%0a真のナポリピッツァ協会認定店%20「#{@post.shop.name}」%0a&hashtags=真のナポリピッツァ部,真のナポリピッツァ協会 ", title: 'Twitter', target: '_blank', class: 'btn btn-outline-primary rounded-pill mt-2 mb-5' do %>
            <i class="fab fa-twitter"></i>
            <span><%= (t 'shops.show.share') %></span>
          <% end %>
        </div>
        <div class='font-weight-bold text-center col-7 col-sm-3'>
        <%= link_to user_path(@post.user) do %>
          <%= image_tag @post.user.avatar_url, class: 'rounded-circle my-2', size: '120x120' %>
          <p class='text-dark'><%= @post.user.name %></p>
        </div>
        <% end %>
        <p class='font-weight-bold mt-4 ml-3'><%= @post.title %></p>
        <p class='ml-3'><%= simple_format(h(@post.body)) %></p>
        <% @post.image.each do |image| %>
          <%= image_tag image.url, class: 'rounded m-1 img-fluid', data: { toggle: 'modal', target: "#image-modal#{@post.shop_id += 1}" }, size: '230x180', 'data-turbolinks': false, style: "cursor:pointer" %>
          <div class="modal fade" id="image-modal<%= @post.shop_id%>">
            <div class="modal-dialog modal-lg modal-middle">
              <div class="modal-body">
                <%= image_tag image.url, class: 'img-fluid rounded m-1' %>
              </div>
            </div>
          </div>
        <%end%>
        <p><%= @post.set_date %></p>
        <% if current_user?(@post.user) %>
          <%= link_to post_path(@post), method: :delete, data: { confirm: '削除しますか？' } do %>
            <%= icon 'fas', 'trash' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>